Patch Rook 1.0.4 to Ceph 14.2.21
replicatedhq/kURL pull request #1726
Opened 2021-06-15 19:20 UTC by murphybytes

See [Clubhouse Issue](https://app.clubhouse.io/replicated/story/34494/upgrade-ceph-image-to-latest-nautilus-in-rook-1-0-4-addon)

2021-06-15 19:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/replicatedhq/kURL?pullRequest=1726) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/replicatedhq/kURL?pullRequest=1726) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/replicatedhq/kURL?pullRequest=1726) it.</sub>

2021-06-16 15:54 UTC, emosbaugh commented
Would you mind adding the diff output of `diff addons/rook/1.0.4 addons/rook/1.0.4-14.2.21`?

Also it looks like upgrades are [failing in testgrid](https://testgrid.kurl.sh/run/pr-1726-b6f6971-rook-1.0.4-14.2.21-k8s-docker?kurlLogsInstanceId=pghrcy#L774). I think we will only have to support upgrades from `1.0.4` to `1.0.4-14.2.21` as we don't currently support upgrades from `1.0.4` to any other version.

2021-06-16 19:25 UTC, murphybytes commented
diff --color -r 1.0.4/build-images/ceph/Dockerfile 1.0.4-14.2.21/build-images/ceph/Dockerfile
3c3
< FROM ceph/ceph:v14.2.0
---
> FROM ceph/ceph:v14.2.21
5,32d4
< RUN yum install -y \
<     bind-license \
<     curl \
<     glibc \
<     glibc-common \
<     libcurl \
<     libwbclient \
<     openssl \
<     openssl-libs \
<     perl \
<     perl-Pod-Escapes \
<     perl-libs \
<     perl-macros \
<     python \
<     python-devel \
<     python-libs \
<     python-rtslib \
<     python3 \
<     python3-libs \
<     samba-client-libs \
<     sudo \
<     libldb \
<     nettle \
<     nss \
<     nss-sysinit \
<     nss-tools \
<     openldap \
<   && yum clean all
diff --color -r 1.0.4/build-images/ceph/Makefile 1.0.4-14.2.21/build-images/ceph/Makefile
3c3
< IMAGE := kurlsh/ceph:v14.2.0
---
> IMAGE := kurlsh/ceph:v14.2.21
diff --color -r 1.0.4/build-images/rook-ceph/Dockerfile 1.0.4-14.2.21/build-images/rook-ceph/Dockerfile
5,34c5
< FROM ceph/ceph:v14.2.0
< 
< RUN yum install -y \
<     bind-license \
<     curl \
<     glibc \
<     glibc-common \
<     libcurl \
<     libwbclient \
<     openssl \
<     openssl-libs \
<     perl \
<     perl-Pod-Escapes \
<     perl-libs \
<     perl-macros \
<     python \
<     python-devel \
<     python-libs \
<     python-rtslib \
<     python3 \
<     python3-libs \
<     samba-client-libs \
<     sudo \
<     libldb \
<     nettle \
<     nss \
<     nss-sysinit \
<     nss-tools \
<     openldap \
<   && yum clean all
---
> FROM ceph/ceph:v14.2.21
diff --color -r 1.0.4/build-images/rook-ceph/Makefile 1.0.4-14.2.21/build-images/rook-ceph/Makefile
3c3
< IMAGE := kurlsh/rook-ceph:v1.0.4
---
> IMAGE := kurlsh/rook-ceph:v1.0.4-14.2.21
diff --color -r 1.0.4/install.sh 1.0.4-14.2.21/install.sh
1a2
> 
4c5
<         bail "Rook 1.0.4 is not compatible with Kubernetes 1.20+"
---
>         bail "Rook ${ROOK_VERSION} is not compatible with Kubernetes 1.20+"
27c28
<     kubectl apply -f "$DIR/addons/rook/1.0.4/cluster/object-user.yaml"
---
>     kubectl apply -f "$DIR/addons/rook/${ROOK_VERSION}/cluster/object-user.yaml"
37c38
<     local src="$DIR/addons/rook/1.0.4/operator"
---
>     local src="$DIR/addons/rook/${ROOK_VERSION}/operator"
45c46
<     local src="$DIR/addons/rook/1.0.4/cluster"
---
>     local src="$DIR/addons/rook/${ROOK_VERSION}/cluster"
diff --color -r 1.0.4/operator/ceph-operator.yaml 1.0.4-14.2.21/operator/ceph-operator.yaml
37c37
<         image: kurlsh/rook-ceph:v1.0.4-998b6b6-20210430
---
>         image: kurlsh/rook-ceph:v1.0.4-14.2.21-bf6be4c-20210616

2021-06-16 19:27 UTC, murphybytes commented
> Would you mind adding the diff output of `diff addons/rook/1.0.4 addons/rook/1.0.4-14.2.21`?
> 
> Also it looks like upgrades are [failing in testgrid](https://testgrid.kurl.sh/run/pr-1726-b6f6971-rook-1.0.4-14.2.21-k8s-docker?kurlLogsInstanceId=pghrcy#L774). I think we will only have to support upgrades from `1.0.4` to `1.0.4-14.2.21` as we don't currently support upgrades from `1.0.4` to any other version.

```diff
diff --color -r 1.0.4/build-images/ceph/Dockerfile 1.0.4-14.2.21/build-images/ceph/Dockerfile
3c3
< FROM ceph/ceph:v14.2.0
---
> FROM ceph/ceph:v14.2.21
5,32d4
< RUN yum install -y \
<     bind-license \
<     curl \
<     glibc \
<     glibc-common \
<     libcurl \
<     libwbclient \
<     openssl \
<     openssl-libs \
<     perl \
<     perl-Pod-Escapes \
<     perl-libs \
<     perl-macros \
<     python \
<     python-devel \
<     python-libs \
<     python-rtslib \
<     python3 \
<     python3-libs \
<     samba-client-libs \
<     sudo \
<     libldb \
<     nettle \
<     nss \
<     nss-sysinit \
<     nss-tools \
<     openldap \
<   && yum clean all
diff --color -r 1.0.4/build-images/ceph/Makefile 1.0.4-14.2.21/build-images/ceph/Makefile
3c3
< IMAGE := kurlsh/ceph:v14.2.0
---
> IMAGE := kurlsh/ceph:v14.2.21
diff --color -r 1.0.4/build-images/rook-ceph/Dockerfile 1.0.4-14.2.21/build-images/rook-ceph/Dockerfile
5,34c5
< FROM ceph/ceph:v14.2.0
< 
< RUN yum install -y \
<     bind-license \
<     curl \
<     glibc \
<     glibc-common \
<     libcurl \
<     libwbclient \
<     openssl \
<     openssl-libs \
<     perl \
<     perl-Pod-Escapes \
<     perl-libs \
<     perl-macros \
<     python \
<     python-devel \
<     python-libs \
<     python-rtslib \
<     python3 \
<     python3-libs \
<     samba-client-libs \
<     sudo \
<     libldb \
<     nettle \
<     nss \
<     nss-sysinit \
<     nss-tools \
<     openldap \
<   && yum clean all
---
> FROM ceph/ceph:v14.2.21
diff --color -r 1.0.4/build-images/rook-ceph/Makefile 1.0.4-14.2.21/build-images/rook-ceph/Makefile
3c3
< IMAGE := kurlsh/rook-ceph:v1.0.4
---
> IMAGE := kurlsh/rook-ceph:v1.0.4-14.2.21
diff --color -r 1.0.4/install.sh 1.0.4-14.2.21/install.sh
1a2
> 
4c5
<         bail "Rook 1.0.4 is not compatible with Kubernetes 1.20+"
---
>         bail "Rook ${ROOK_VERSION} is not compatible with Kubernetes 1.20+"
27c28
<     kubectl apply -f "$DIR/addons/rook/1.0.4/cluster/object-user.yaml"
---
>     kubectl apply -f "$DIR/addons/rook/${ROOK_VERSION}/cluster/object-user.yaml"
37c38
<     local src="$DIR/addons/rook/1.0.4/operator"
---
>     local src="$DIR/addons/rook/${ROOK_VERSION}/operator"
45c46
<     local src="$DIR/addons/rook/1.0.4/cluster"
---
>     local src="$DIR/addons/rook/${ROOK_VERSION}/cluster"
diff --color -r 1.0.4/operator/ceph-operator.yaml 1.0.4-14.2.21/operator/ceph-operator.yaml
37c37
<         image: kurlsh/rook-ceph:v1.0.4-998b6b6-20210430
---
>         image: kurlsh/rook-ceph:v1.0.4-14.2.21-bf6be4c-20210616

```

2021-06-17 00:14 UTC, emosbaugh commented
Upgrade looks good in testgrid. Were you able to manually validate ceph status after an upgrade?

2021-06-20 18:38 UTC, murphybytes commented
> Upgrade looks good in testgrid. Were you able to manually validate ceph status after an upgrade?

@emosbaugh yep, looks good.

2021-06-21 16:55 UTC, emosbaugh requested changes

2021-06-21 16:55 UTC, emosbaugh commented on addons/rook/template/testgrid/k8s-docker.yaml
> +    rook:
this looks like it was truncated or duplicated or something...

2021-06-21 18:09 UTC, emosbaugh commented
Additionally you will have to add the version to the bottom of this list

https://github.com/replicatedhq/kURL/blob/03f7d70b259792ff990370f1b6112621508662de/web/src/installers/versions.js#L60

2021-06-21 21:20 UTC, emosbaugh approved these changes

2021-06-22 18:52 UTC, merged