Kwsorensen/rook ceph secure global
replicatedhq/kURL pull request #1729
Opened 2021-06-17 15:26 UTC by kwsorensen

Pull request to fix [HEALTH_WARN mon is allowing insecure global_id reclaim
](https://docs.ceph.com/en/latest/security/CVE-2021-20288/)

2021-06-17 16:41 UTC, MikaelSmith commented
https://github.com/rook/rook/releases/tag/v1.6.5 has their own work to address this. But maybe the kURL environment is simple enough that you don't need to worry about outdated clients during the upgrade process.

2021-06-17 20:33 UTC, laverya commented
I would recommend (instead of this) 
1. make this change: addons/rook/1.5.11/operator/configmap-rook-config-override.yaml
2. make the same change in templates (addons/rook/templates/base/operator/configmap-rook-config-override.yaml)
3. let automation make 1.5.12

2021-06-21 18:15 UTC, kwsorensen commented
Ways Tested:
Fresh install with fixed version 5.11 - good
Fresh install with fixed version 5.12 - good
Fresh install with un-fixed version 5.11 into a fixed version 5.12 - Ceph status still shows errors.

2021-06-22 17:07 UTC, areed reviewed
https://github.com/replicatedhq/kURL/pull/1729/files#diff-5041c635371838ae5901774a8bcf202a1543309d1462226eb36278b4a07da8f9R182

Calling `rook_patch_insecure_clients` here would fix re-install of 1.5.11 with the `force-reapply-addons` flag.

2021-06-22 17:47 UTC, areed approved these changes
This disables insecure global_id reclaim after all clients have been patched to authenticate correctly.

2021-06-22 17:52 UTC, emosbaugh requested changes

2021-06-22 17:52 UTC, emosbaugh commented on addons/rook/1.5.11/install.sh
> +       then return 1
you dont need `fi`? for readability can you change to this format?

```
if ... ; then
  return 1
fi

2021-06-22 18:10 UTC, emosbaugh approved these changes

2021-06-22 18:10 UTC, emosbaugh approved these changes

2021-06-22 18:19 UTC, merged