Adding option to specify advanced flags
replicatedhq/kURL pull request #2531
Opened 2021-12-21 22:13 UTC by jdewinne

2021-12-21 22:14 UTC, jdewinne commented
This is needed in order to be able to write an automated test for the labels flag
https://github.com/replicatedhq/kURL/pull/2445

2022-01-06 15:10 UTC, DanStough requested changes
I think the modal is overkill but feel free to disagree.

2022-01-06 15:10 UTC, DanStough commented on testgrid/web/src/components/views/InstanceTable.jsx
> +              }
Do you think there is an advantage for opening the modal here? 

```suggestion
            {this.props.instancesMap[kurlUrl][0].kurlFlags &&
              <span> [{this.props.instancesMap[kurlUrl][0].kurlFlags}] </span>
              }
```

You need to remove the state change if you opt for this.

2022-08-03 23:15 UTC, emosbaugh commented
Looks like this was merged in https://github.com/replicatedhq/kURL/pull/2736. Closing

2022-08-03 23:15 UTC, closed without merging