fix golang lint errors shown on github PRs
replicatedhq/kURL pull request #2983
Opened 2022-06-03 16:18 UTC by laverya

#### What type of PR is this?

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

## Steps to reproduce

#### Does this PR introduce a user-facing change?

```release-note

```

#### Does this PR require documentation?

2022-11-22 12:22 UTC, camilamacedo86 reviewed
Hi @laverya,

It seems outdated.
Should we rebase with master or just close this one?

2022-12-21 18:18 UTC, emosbaugh approved these changes

2022-12-21 18:19 UTC, emosbaugh requested changes
tests are failing

```

/home/runner/go/bin/golangci-lint --build-tags "netgo containers_image_ostree_stub exclude_graphdriver_devicemapper exclude_graphdriver_btrfs containers_image_openpgp" run --timeout 5m ./cmd/... ./pkg/... ./kurl_util/...
Error: pkg/cli/commands.go:28:17: undeclared name: `NewSyncObjectStoreCmd` (typecheck)
	cmd.AddCommand(NewSyncObjectStoreCmd(cli))
	               ^
make: *** [Makefile:622: lint] Error 1
```

2022-12-21 19:35 UTC, emosbaugh approved these changes

2022-12-21 19:35 UTC, merged