Add host preflight check for Docker Addon on Ubuntu 22.04
replicatedhq/kURL pull request #3265
Opened 2022-08-08 23:33 UTC by rrpolanco

#### What type of PR is this?

type::feature

#### What this PR does / why we need it:

Current supported kURL versions of Docker are not yet supported on Ubuntu 22.04

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

## Steps to reproduce

#### Does this PR introduce a user-facing change?

```release-note
- New preflight check to disallow Docker addon install on Ubuntu 22.04

```

#### Does this PR require documentation?

Yes

2022-08-08 23:34 UTC, rrpolanco commented
Tested on `Ubuntu 22.04` Server:

```bash
rafael@rafael-kurl:~$ cat install.sh | sudo bash
SELinux is not installed: no configuration will be applied
The installer will use network interface 'ens4' (with IP address '10.128.0.82')
⚙  Running host preflights
[TCP Port Status] Running collector...
[CPU Info] Running collector...
[Amount of Memory] Running collector...
[Block Devices] Running collector...
[Host OS Info] Running collector...
[Ephemeral Disk Usage /var/lib/kubelet] Running collector...
[Ephemeral Disk Usage /var/lib/docker] Running collector...
[Kubernetes API TCP Port Status] Running collector...
[ETCD Client API TCP Port Status] Running collector...
[ETCD Server API TCP Port Status] Running collector...
[ETCD Health Server TCP Port Status] Running collector...
[Kubelet Health Server TCP Port Status] Running collector...
[Kubelet API TCP Port Status] Running collector...
[Kube Controller Manager Health Server TCP Port Status] Running collector...
[Kube Scheduler Health Server TCP Port Status] Running collector...
[Filesystem Latency Two Minute Benchmark] Running collector...
[PASS] Number of CPUs: This server has at least 4 CPU cores
[PASS] Amount of Memory: The system has at least 8G of memory
[PASS] Ephemeral Disk Usage /var/lib/kubelet: The disk containing directory /var/lib/kubelet has at least 30Gi of total space, has at least 10Gi of disk space available, and is less than 60% full
[PASS] Ephemeral Disk Usage /var/lib/docker: The disk containing directory /var/lib/docker has at least 30Gi of total space, has at least 10Gi of disk space available, and is less than 60% full.
[PASS] Kubernetes API TCP Port Status: Port 6443 is open
[PASS] ETCD Client API TCP Port Status: Port 2379 is open
[PASS] ETCD Server API TCP Port Status: Port 2380 is open
[PASS] ETCD Health Server TCP Port Status: Port 2381 is available
[PASS] Kubelet Health Server TCP Port Status: Port 10248 is available
[PASS] Kubelet API TCP Port Status: Port 10250 is open
[PASS] Kube Controller Manager Health Server TCP Port Status: Port 10257 is available
[PASS] Kube Scheduler Health Server TCP Port Status: Port 10259 is available
[PASS] Filesystem Performance: Write latency is ok (p99 target < 10ms, actual: 9.189825ms)
[PASS] NTP Status: System clock is synchronized
[PASS] NTP Status: Timezone is set to UTC
[FAIL] Docker on Ubuntu 22.04: docker addon does not support ubuntu 22.04
Host preflights have failures that block the installation.
```

2022-08-08 23:36 UTC, sgalsaleh approved these changes

2022-08-08 23:37 UTC, emosbaugh requested changes

2022-08-08 23:37 UTC, emosbaugh commented on pkg/preflight/assets/host-preflights.yaml
> +              message: "docker addon does not support ubuntu 22.04"
Can you capitalize Docker?

2022-08-08 23:41 UTC, rrpolanco commented on pkg/preflight/assets/host-preflights.yaml
> +              message: "docker addon does not support ubuntu 22.04"
Updated.

2022-08-09 00:00 UTC, jala-dx approved these changes

2022-08-09 00:06 UTC, merged