add a type::feature label to automated addon PRs
replicatedhq/kURL pull request #3301
Opened 2022-08-17 16:07 UTC by laverya

#### What this PR does / why we need it:

Without a type label, PRs are marked as failing CI.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

## Steps to reproduce

#### Does this PR introduce a user-facing change?

```release-note

```

#### Does this PR require documentation?

2022-08-17 17:27 UTC, rrpolanco approved these changes

2022-08-22 03:24 UTC, rrpolanco submitted a review, later dismissed

2022-08-22 04:30 UTC, emosbaugh reviewed
@AmberAlston i believe keeping add-ons up to date is considered a chore correct?

2022-08-22 15:15 UTC, AmberAlston commented
@emosbaugh Correct. Keeping add-ons up-to-date and patched is currently labeled a chore.

2022-08-29 15:43 UTC, emosbaugh commented
@laverya can we get this updated with type::chore so we can merge?

2022-08-29 16:07 UTC, emosbaugh requested changes

2022-08-29 16:07 UTC, emosbaugh commented on .github/workflows/update-containerd.yaml
> +            Added [Containerd](https://kurl.sh/docs/add-ons/containerd) ${{ steps.update.outputs.containerd_version }}
Can you follow the pattern we use in release notes?

```suggestion
            Adds [Containerd add-on](https://kurl.sh/docs/add-ons/containerd) version(s) ${{ steps.update.outputs.containerd_version }}.

2022-08-29 16:14 UTC, emosbaugh commented on .github/workflows/update-containerd.yaml
> +            Added [Containerd](https://kurl.sh/docs/add-ons/containerd) ${{ steps.update.outputs.containerd_version }}
For continerd can you change output for containerd_version to:

```
    echo "::set-output name=containerd_version::${VERSIONS[*]}"
```

2022-08-29 16:35 UTC, emosbaugh requested changes

2022-08-29 16:35 UTC, emosbaugh commented on .github/workflows/update-kubernetes.yaml
> +            Adds [Kubernetes](https://kurl.sh/docs/add-ons/kubernetes) version ${{ steps.update.outputs.kubernetes_version }}
```suggestion
            Adds [Kubernetes](https://kurl.sh/docs/add-ons/kubernetes) version(s) ${{ steps.update.outputs.kubernetes_version }}
```

https://github.com/replicatedhq/kURL/pull/3303

2022-08-29 16:35 UTC, emosbaugh commented on .github/workflows/update-kotsadm.yaml
> +            Adds [kOTS add-on](https://kurl.sh/docs/add-ons/kotsadm) version ${{ steps.update.outputs.kotsadm_version }}
```suggestion
            Adds [KOTS add-on](https://kurl.sh/docs/add-ons/kotsadm) version ${{ steps.update.outputs.kotsadm_version }}
```

2022-08-29 16:35 UTC, emosbaugh commented on .github/workflows/update-sonobuoy.yaml
> +            Adds [SonoBouy add-on](https://kurl.sh/docs/add-ons/sonobouy) version ${{ steps.update.outputs.sonobouy_version }}
```suggestion
            Adds [Sonobouy add-on](https://kurl.sh/docs/add-ons/sonobouy) version ${{ steps.update.outputs.sonobouy_version }}
```

2022-08-29 16:35 UTC, emosbaugh commented on .github/workflows/update-velero.yaml
> +            Adds [Velero add-on](https://kurl.sh/docs/add-ons/veler) version ${{ steps.update.outputs.veler_version }}
```suggestion
            Adds [Velero add-on](https://kurl.sh/docs/add-ons/velero) version ${{ steps.update.outputs.velero_version }}
```

2022-08-29 16:35 UTC, emosbaugh commented on .github/workflows/update-goldpinger.yaml
> +            Adds [GoldPinger add-on](https://kurl.sh/docs/add-ons/goldpinger) version ${{ steps.update.outputs.goldpinger_version }}
```suggestion
            Adds [Goldpinger add-on](https://kurl.sh/docs/add-ons/goldpinger) version ${{ steps.update.outputs.goldpinger_version }}
```

2022-08-29 17:16 UTC, emosbaugh approved these changes

2022-08-29 17:17 UTC, merged