always validate rook scale when rerunning the installer
replicatedhq/kURL pull request #3386
Opened 2022-08-29 21:48 UTC by laverya

#### What this PR does / why we need it:
When EKCO is not installed, the only opportunity we have to control the number of replicas for data in Rook is when running install.sh. For this to happen, that function needs to be called in the _already_applied function.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

## Steps to reproduce

#### Does this PR introduce a user-facing change?

```release-note

```

#### Does this PR require documentation?

2022-08-29 21:50 UTC, emosbaugh requested changes

2022-08-29 21:50 UTC, emosbaugh commented on addons/rook/template/base/install.sh
> +    rook_set_ceph_pool_replicas
the lines are revered

2022-08-29 21:50 UTC, laverya commented on addons/rook/template/base/install.sh
> +    rook_set_ceph_pool_replicas
🤦

2022-08-29 21:51 UTC, emosbaugh approved these changes

2022-08-30 17:36 UTC, rrpolanco approved these changes

2022-08-30 17:46 UTC, merged