update label for troubleshoot/918
replicatedhq/kURL pull request #3874
Opened 2022-12-19 21:53 UTC by adamancini

https://github.com/replicatedhq/troubleshoot/pull/918 changes the label used by Troubleshoot to be more consistent with the data key in the spec

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

## Steps to reproduce

#### Does this PR introduce a user-facing change?

```release-note
NONE

```

#### Does this PR require documentation?

NONE

2022-12-20 00:01 UTC, emosbaugh requested changes
can you update it here as well? thanks

https://github.com/replicatedhq/kURL/blob/main/addons/flannel/0.20.2/yaml/troubleshoot.yaml

2022-12-20 18:55 UTC, adamancini commented
@emosbaugh done

2022-12-20 20:01 UTC, emosbaugh approved these changes

2022-12-21 07:27 UTC, camilamacedo86 commented
Hi @adamancini,

You will be unable to run the tests because it is a fork.  
Could open this one as a new branch of the project instead?

2022-12-21 17:54 UTC, emosbaugh commented
I'm going to merge this without testgrid tests for now as it looks to be safe

2022-12-21 17:54 UTC, merged