Always re-apply addons
replicatedhq/kURL pull request #4220
Opened 2023-03-20 15:21 UTC by rrpolanco

#### What this PR does / why we need it:

Part of the kURL addon lifecyle includes an `addon_already_applied` phase which attempts to avoid deploying the addon again. For certain addons there is a complexity overhead to keep to use of this logic and in certain scenarios there are issues with simply just re-configuring an existing addon when the kURL installer is re-run which leads to an inconsistent state of the cluster.

Moreover, the `--force-reapply-addon` flag will no longer be supported as this will now be the default behavior:
```sh
$ cat install.sh | sudo bash -s force-reapply-addons
⚙  Running install with the argument(s): force-reapply-addons
Error: unknown parameter "force-reapply-addons"
```

#### Which issue(s) this PR fixes:

Fixes  [sc-70122](https://app.shortcut.com/replicated/story/70122/addon-already-applied-has-potential-to-break-things-especially-when-upgrading-some-but-not-all-add-ons)

#### Special notes for your reviewer:

## Steps to reproduce

#### Does this PR introduce a user-facing change?

```release-note
The kURL installer will now force reapply addons by default deprecating the usage of the `force-reapply-addons` options. 
```

#### Does this PR require documentation?
https://github.com/replicatedhq/kurl.sh/pull/950

2023-03-23 19:22 UTC, emosbaugh commented on scripts/common/addon.sh
> -        export REPORTING_CONTEXT_INFO=""
i think you lost this line

2023-03-23 20:32 UTC, rrpolanco commented on addons/containerd/template/base/install.sh
> +    # only install if package is not present
I see. I'll change this so that `preserveConfig` continues to behave as before.

2023-03-24 20:43 UTC, emosbaugh requested changes
what happened to that CONTAINERD_PRESERVE_CONFIG logic? i quite liked that. i just dont think you can reappropriate the variable because our vendors are already using it.

2023-03-24 20:43 UTC, emosbaugh commented on kurl_util/cmd/bashmerge/main.go
> -		case "force-reapply-addons":
can you leave this for backwards compatibility and add a comment?

2023-03-24 20:43 UTC, emosbaugh commented on scripts/common/utilbinaries.sh
> -            force-reapply-addons)
can you leave this for backwards compatibility and add a comment?

2023-03-24 22:03 UTC, emosbaugh requested changes
can you remove remove get_force_reapply_addons_flag again? appending that flag is only perpetuating the problem. i only asked that you add back the switch statements.

2023-03-24 22:21 UTC, emosbaugh approved these changes

2023-03-24 22:28 UTC, merged