Increase Flannel waiting and improve log
replicatedhq/kURL pull request #4567
Opened 2023-05-30 14:29 UTC by camilamacedo86

#### What this PR does / why we need it:

See that if the script fails to get the logs:

```
⚙  Addon flannel 0.21.5
namespace/kube-flannel unchanged
serviceaccount/flannel unchanged
clusterrole.rbac.authorization.k8s.io/flannel unchanged
clusterrolebinding.rbac.authorization.k8s.io/flannel unchanged
configmap/kube-flannel-cfg unchanged
secret/flannel-troubleshoot-spec configured
daemonset.apps/kube-flannel-ds unchanged
waiting for Flannel to become healthy
Error from server: Get "https://10.154.0.89:10250/containerLogs/kube-flannel/kube-flannel-ds-bznsb/kube-flannel?tailLines=10": net/http: TLS handshake timeout
An error occurred on line 146
```

It will fail with `An error occurred on line 146` instead of the bail message.
This PR improve the waiting time for 5 minutes and adds || to avoid fails with error script line instead of the bail message

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

## Steps to reproduce

#### Does this PR introduce a user-facing change?

```release-note
Increase the Flannel waiting time to check that it is available and improve log in case of failures. This change are valid only for Flannel versions equals and upper than `0.21.5`. 
```

#### Does this PR require documentation?

2023-05-30 15:27 UTC, rrpolanco approved these changes
LGTM. However, if we have to increase the timeout more than 5 mins. that should prompt us to investigate what's taking so long.

2023-05-30 16:14 UTC, laverya commented on addons/flannel/0.21.5/install.sh
> +        kubectl logs -n kube-flannel -l app=flannel --all-containers --tail 10 || true
```suggestion
    echo "Waiting up 5 minutes for Flannel to become healthy"
    if ! spinner_until 300 flannel_health_check; then
        kubectl logs -n kube-flannel -l app=flannel --all-containers --tail 10 || true
```

2023-05-30 16:14 UTC, laverya commented on addons/flannel/template/base/install.sh
> +    echo "Waiting for Flannel to become healthy up 5 minutes"
```suggestion
    echo "Waiting up 5 minutes for Flannel to become healthy"
```

2023-05-30 16:14 UTC, laverya requested changes
grammar changes

2023-05-30 19:33 UTC, laverya commented on addons/flannel/0.21.5/install.sh
> +    echo "Waiting up 5 minutes for Flannel to become healthy"
🤦 my bad

2023-05-30 22:42 UTC, rrpolanco approved these changes

2023-05-31 20:08 UTC, laverya approved these changes

2023-05-31 20:10 UTC, merged